name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  build_configuration: Release
  project_path: ./Backend(IA)/VendorHub.API.csproj

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Frontend(IA)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop-frontend
          path: .

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies
        run: dotnet restore "${{ env.project_path }}"

      - name: Build Backend
        run: dotnet build "${{ env.project_path }}" --configuration ${{ env.build_configuration }} --no-restore

      - name: Publish Backend
        run: dotnet publish "${{ env.project_path }}" --configuration ${{ env.build_configuration }} --no-build --output ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: ./publish